"""empty message

Revision ID: 27b3191b1f37
Revises: 070bf36ab323
Create Date: 2023-08-07 18:59:50.980289

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '27b3191b1f37'
down_revision = '070bf36ab323'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('post_text',
    sa.Column('post_id', sa.Integer(), nullable=True),
    sa.Column('teg_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['post_id'], ['post.id'], ),
    sa.ForeignKeyConstraint(['teg_id'], ['tag.id'], )
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('post_text')
    # ### end Alembic commands ###
